"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------
# Security / Core
# ----------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "change-me-please")

DEBUG = os.getenv("DJANGO_DEBUG", "0") in ("1", "true", "True", "yes", "YES")

# ALLOWED_HOSTS from env (comma-separated). fallback to safe defaults.
_default_hosts = [
    "shopify.kidstoyloverapps.com",
    "tickets.kidstoyloverapps.com",
    "orders.kidstoyloverapps.com",
    ".kidstoyloverapps.com",
    "localhost",
    "127.0.0.1",
    ".trycloudflare.com",
]
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", ",".join(_default_hosts)).split(",") if h.strip()]

# CSRF trusted origins from env (comma-separated)
_default_csrf = [
    "https://shopify.kidstoyloverapps.com",
    "https://tickets.kidstoyloverapps.com",
    "https://orders.kidstoyloverapps.com",
    "https://*.kidstoyloverapps.com",
    "https://*.trycloudflare.com",
]
CSRF_TRUSTED_ORIGINS = [u.strip() for u in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", ",".join(_default_csrf)).split(",") if u.strip()]

# When behind Cloudflare Tunnel / reverse proxy:
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ----------------------------
# Application definition
# ----------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tickets",
    "shopify_sync",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise: serve static files even when DEBUG=False
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "config.wsgi.application"

# ----------------------------
# Database
# ----------------------------
# Default: sqlite3 (keeps your existing db.sqlite3)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# If you later want Postgres, you can implement DATABASE_URL parsing here.
# (For now, simplest = keep sqlite stable.)

# ----------------------------
# Password validation
# ----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ----------------------------
# Internationalization
# ----------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# ----------------------------
# Static files (CSS, JavaScript, Images)
# ----------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise storage (no manifest,更稳，避免“找不到静态文件hash”导致404)
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# ----------------------------
# Media uploads
# ----------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", str(BASE_DIR / "media"))

# ----------------------------
# Admin UI titles
# ----------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
ADMIN_SITE_HEADER = "kidstoylover"
ADMIN_SITE_TITLE = "kidstoylover Admin"
LOGIN_URL = "/admin/login/"
ADMIN_INDEX_TITLE = "kidstoylover 后台管理"
