# Generated by Django 5.2.10 on 2026-01-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='product_sku',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='客户邮箱'),
        ),
    ]
