# Generated by Django 5.2.11 on 2026-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketattachment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='pending_followup_to',
            field=models.CharField(blank=True, choices=[('ops', 'zhang-SupportOps'), ('cs', 'CustomerSupport')], help_text='管理员可指定下一步由谁跟进（留空则按自动逻辑判断）', max_length=20, null=True, verbose_name='指定待跟进'),
        ),
    ]
