# Generated by Django 5.2.11 on 2026-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketcomment_pending_followup_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='pending_followup_to',
            field=models.CharField(blank=True, choices=[('ops', 'zhang-SupportOps'), ('cs', 'CustomerSupport')], default='ops', help_text='管理员可指定下一步由谁跟进（默认 zhang-SupportOps）', max_length=20, verbose_name='指定待跟进'),
        ),
    ]
