# Generated by Django 5.2.11 on 2026-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticketcomment_pending_followup_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='pending_followup_to',
            field=models.CharField(blank=True, choices=[('ops', 'zhang-SupportOps'), ('cs', 'CustomerSupport')], default='', help_text='留空则使用自动判断逻辑；管理员可显式指定由谁跟进', max_length=20, verbose_name='指定待跟进'),
        ),
    ]
