# Generated by Django 5.2.11 on 2026-02-09 11:32

from django.db import migrations


def clear_ops_values(apps, schema_editor):
    """将所有旧的 pending_followup_to='ops' 改为空字符串"""
    TicketComment = apps.get_model('tickets', 'TicketComment')
    TicketComment.objects.filter(pending_followup_to='ops').update(pending_followup_to='')
    print("✓ 已清除所有旧的 pending_followup_to='ops' 值")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketcomment_pending_followup_to'),
    ]

    operations = [
        migrations.RunPython(clear_ops_values),
    ]
