# Generated by Django 5.2.11 on 2026-02-09 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_clear_pending_followup_to_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='pending_followup_to',
            field=models.CharField(blank=True, choices=[('ops', 'zhang-SupportOps'), ('cs', 'CustomerSupport'), ('admin', 'admin')], default='', help_text='留空则使用自动判断逻辑；管理员/客服可显式指定由谁跟进', max_length=20, verbose_name='指定待跟进'),
        ),
        migrations.CreateModel(
            name='TicketReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最后查看时间')),
                ('last_seen_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_by', to='tickets.ticketcomment', verbose_name='最后查看的回复')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='tickets.ticket', verbose_name='工单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
