# Generated by Django 5.2.13 on 2026-05-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0003_shopify_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_line_item_id', models.BigIntegerField()),
                ('shopify_product_id', models.BigIntegerField(blank=True, null=True)),
                ('shopify_variant_id', models.BigIntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('product_title', models.CharField(blank=True, max_length=255)),
                ('variant_title', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fulfillment_location', models.CharField(blank=True, max_length=255)),
                ('locked_product_cost_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('locked_shipping_cost_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('handling_fee_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shopifyorder',
            options={'ordering': ['-order_created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='shopifyorder',
            name='unique_installation_order',
        ),
        migrations.RemoveConstraint(
            model_name='shopifyproduct',
            name='unique_installation_variant',
        ),
        migrations.RenameField(
            model_name='shopifyorder',
            old_name='created_at',
            new_name='order_created_at',
        ),
        migrations.RenameIndex(
            model_name='shopifyproduct',
            new_name='shopify_syn_install_92b439_idx',
            old_name='shopify_syn_install_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproduct',
            new_name='shopify_syn_shopify_7fbdde_idx',
            old_name='shopify_syn_variant_idx',
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='is_shenzhen_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='original_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='settlement_status',
            field=models.CharField(choices=[('pending_warehouse', '待深圳仓确认'), ('warehouse_fulfilled', '深圳仓已发货'), ('cost_confirmed', '深圳仓已确认成本'), ('admin_confirmed', 'admin已确认'), ('pending_payment', '待支付'), ('paid', '已支付'), ('transferred', '已转其他仓'), ('cancelled', '已取消深圳仓履约'), ('exception', '异常待审核')], default='pending_warehouse', max_length=20),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyorder',
            unique_together={('installation', 'shopify_order_id')},
        ),
        migrations.AlterUniqueTogether(
            name='shopifyproduct',
            unique_together={('installation', 'shopify_variant_id')},
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['is_shenzhen_order', 'settlement_status'], name='shopify_syn_is_shen_60811a_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['order_created_at'], name='shopify_syn_order_c_d20b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['current_location'], name='shopify_syn_current_fec5a8_idx'),
        ),
        migrations.AddField(
            model_name='shopifyorderitem',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shopify_sync.shopifyproduct'),
        ),
        migrations.AddField(
            model_name='shopifyorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shopify_sync.shopifyorder'),
        ),
        migrations.AddIndex(
            model_name='shopifyorderitem',
            index=models.Index(fields=['shopify_variant_id'], name='shopify_syn_shopify_4a6263_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorderitem',
            index=models.Index(fields=['sku'], name='shopify_syn_sku_3a1627_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorderitem',
            index=models.Index(fields=['fulfillment_location'], name='shopify_syn_fulfill_8b0859_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyorderitem',
            unique_together={('order', 'shopify_line_item_id')},
        ),
    ]
