# Generated by Django 5.2.13 on 2026-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0004_shopifyorderitem_alter_shopifyorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='current_location_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='original_location_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
