# Generated by Django 5.2.13 on 2026-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0006_alter_shopifyorder_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='fulfillment_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='variant_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
