# Generated by Django 5.2.13 on 2026-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0007_alter_shopifyorderitem_fulfillment_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='warehouse_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
