# Generated by Django 5.2.13 on 2026-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0009_shopifyorder_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='高 cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='长 cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shipping_note',
            field=models.TextField(blank=True, help_text='运费备注'),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='volume_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='体积重 kg（自动计算）', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='实际重量 kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='宽 cm', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ShippingCostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='规则名称', max_length=255)),
                ('country_code', models.CharField(help_text='国家代码，例如 AU, US, DE, FR', max_length=3)),
                ('country_name', models.CharField(help_text='国家名称', max_length=255)),
                ('min_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('use_volume_weight', models.BooleanField(default=False, help_text='是否启用体积重')),
                ('volume_divisor', models.DecimalField(decimal_places=2, default=6000, help_text='体积重除数，默认 6000', max_digits=10)),
                ('price_per_kg_rmb', models.DecimalField(decimal_places=2, help_text='每 kg 运费 RMB', max_digits=10)),
                ('base_fee_rmb', models.DecimalField(decimal_places=2, default=0, help_text='基础费用 RMB', max_digits=10)),
                ('handling_fee_rmb', models.DecimalField(decimal_places=2, default=0, help_text='下单费 / 操作费 RMB', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['country_code', 'name'],
                'indexes': [models.Index(fields=['country_code', 'is_active'], name='shopify_syn_country_e13938_idx')],
            },
        ),
    ]
