# Generated by Django 5.2.13 on 2026-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0010_shopifyproduct_height_cm_shopifyproduct_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcostrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='优先级，数字越小优先'),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='chargeable_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单计费重量 kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='cost_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='cost_calculation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='order_handling_fee_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单下单费 RMB', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='order_shipping_cost_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单运费 RMB', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='total_actual_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单实际总重量 kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='total_locked_cost_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单总锁定成本 RMB', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='total_volume_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单体积重 kg', max_digits=10, null=True),
        ),
    ]
