# Generated by Django 5.2.13 on 2026-05-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0011_shippingcostrule_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorder',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='current_location_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='financial_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='original_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='original_location_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
