# Generated by Django 5.2.13 on 2026-05-04 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0012_alter_shopifyorder_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='transfer_note',
            field=models.TextField(blank=True, help_text='转仓备注', null=True),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='transferred_at',
            field=models.DateTimeField(blank=True, help_text='转仓时间', null=True),
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(help_text='批次号，格式: YYYYMM-001', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_payment', '待支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='draft', help_text='批次状态', max_length=20)),
                ('total_amount_rmb', models.DecimalField(decimal_places=2, default=0, help_text='批次总金额 RMB', max_digits=12)),
                ('created_by', models.CharField(blank=True, help_text='创建人', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='支付时间', null=True)),
                ('note', models.TextField(blank=True, help_text='批次备注', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='shopify_syn_status_4d8e10_idx'), models.Index(fields=['batch_no'], name='shopify_syn_batch_n_9b6ebd_idx')],
            },
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='settlement_batch',
            field=models.ForeignKey(blank=True, help_text='所属结算批次', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shopify_sync.settlementbatch'),
        ),
    ]
