# Generated by Django 5.2.13 on 2026-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0013_shopifyorder_transfer_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopifyproduct',
            options={'ordering': ['-shopify_published_at', '-shopify_product_created_at', '-id']},
        ),
        migrations.AddField(
            model_name='shopifyorderitem',
            name='match_note',
            field=models.TextField(blank=True, help_text='匹配备注'),
        ),
        migrations.AddField(
            model_name='shopifyorderitem',
            name='match_status',
            field=models.CharField(choices=[('matched_by_variant_id', '通过 variant_id 匹配'), ('matched_by_sku', '通过 SKU 匹配'), ('matched_by_sku_normalized', '通过 SKU 标准化匹配'), ('unmatched_missing_variant_and_sku', '未匹配：缺少 variant_id 和 SKU'), ('unmatched_variant_not_found', '未匹配：variant_id 未找到'), ('unmatched_sku_not_found', '未匹配：SKU 未找到'), ('custom_item', '自定义商品')], default='unmatched_missing_variant_and_sku', help_text='产品匹配状态', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_product_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_product_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_variant_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_variant_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
