# Generated by Django 5.2.13 on 2026-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0014_alter_shopifyproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
