# Generated by Django 5.2.14 on 2026-05-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0026_exception_review_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShenzhenMergedSettlementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已启用'), ('cancelled', '已取消')], default='draft', max_length=20)),
                ('shipping_name', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_phone', models.CharField(blank=True, default='', max_length=50)),
                ('shipping_address1', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_address2', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_city', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_province', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_zip', models.CharField(blank=True, default='', max_length=20)),
                ('shipping_country', models.CharField(blank=True, default='', max_length=10)),
                ('address_match_key', models.CharField(blank=True, default='', max_length=2048)),
                ('merged_shipping_cost_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('merged_ordering_cost_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shenzhen_merged_settlement_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShenzhenMergedSettlementGroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('address_match_status', models.CharField(choices=[('exact', 'Exact'), ('override', 'Override')], default='exact', max_length=20)),
                ('address_match_key', models.CharField(blank=True, default='', max_length=2048)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_shenzhen_merged_settlement_orders', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='shopify_sync.shenzhenmergedsettlementgroup')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_settlement_group_links', to='shopify_sync.shopifyorder')),
            ],
            options={
                'ordering': ['group', 'added_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='shenzhenmergedsettlementgroup',
            index=models.Index(fields=['status', 'created_at'], name='shenz_merge_grp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shenzhenmergedsettlementgroup',
            index=models.Index(fields=['shipping_country'], name='shenz_merge_grp_country_idx'),
        ),
        migrations.AddIndex(
            model_name='shenzhenmergedsettlementgrouporder',
            index=models.Index(fields=['order', 'added_at'], name='shenz_merge_ord_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='shenzhenmergedsettlementgrouporder',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='shenz_merge_group_order_uniq'),
        ),
    ]
