# Generated by Django 5.2.14 on 2026-05-14 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0027_shenzhenmergedsettlementgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shenzhenmergedsettlementgroup',
            name='settlement_status',
            field=models.CharField(choices=[('pending_warehouse', '待深圳仓确认'), ('cost_confirmed', '深圳仓已确认成本'), ('pending_payment', '待支付'), ('payment_submitted', '已提交支付，待深圳仓确认收款'), ('paid', '已支付')], default='pending_warehouse', max_length=20),
        ),
        migrations.CreateModel(
            name='SettlementBatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('order', '单订单'), ('merged_group', '合并结算组')], max_length=20)),
                ('amount_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效'), ('cancelled', '已取消'), ('paid', '已支付')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlement_batch_entries', to=settings.AUTH_USER_MODEL)),
                ('merged_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batch_entries', to='shopify_sync.shenzhenmergedsettlementgroup')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batch_entries', to='shopify_sync.shopifyorder')),
                ('settlement_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shopify_sync.settlementbatch')),
            ],
            options={
                'ordering': ['settlement_batch', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementBatchEntryCoveredOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_type', models.CharField(choices=[('single_order', '单订单'), ('member_order', '合并组成员订单')], max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_orders', to='shopify_sync.settlementbatchentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_entry_coverages', to='shopify_sync.shopifyorder')),
            ],
            options={
                'ordering': ['entry', 'created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='settlementbatchentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'order'), ('merged_group__isnull', True), ('order__isnull', False)), models.Q(('entry_type', 'merged_group'), ('merged_group__isnull', False), ('order__isnull', True)), _connector='OR'), name='chk_batch_entry_target'),
        ),
        migrations.AddConstraint(
            model_name='settlementbatchentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'order'), ('order__isnull', False)), fields=('settlement_batch', 'order'), name='uniq_batch_entry_order'),
        ),
        migrations.AddConstraint(
            model_name='settlementbatchentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'merged_group'), ('merged_group__isnull', False)), fields=('settlement_batch', 'merged_group'), name='uniq_batch_entry_mgroup'),
        ),
        migrations.AddIndex(
            model_name='settlementbatchentrycoveredorder',
            index=models.Index(fields=['order', 'released_at'], name='entry_cov_order_rel_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementbatchentrycoveredorder',
            constraint=models.UniqueConstraint(fields=('entry', 'order'), name='uniq_entry_covered_order'),
        ),
        migrations.AddConstraint(
            model_name='settlementbatchentrycoveredorder',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('order',), name='uniq_active_covered_order'),
        ),
    ]
