# Generated by Django 5.2.14 on 2026-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0028_shenzhenmergedsettlementgroup_settlement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='shopify_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
